// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ5vUXS2hqImOEl03_vqA3wWx6nfKxpv8',
    appId: '1:12790717908:web:38b3bc66e079b623f60a41',
    messagingSenderId: '12790717908',
    projectId: 'nevents-final',
    authDomain: 'nevents-final-9eba7.firebaseapp.com',
    storageBucket: 'nevents-final.appspot.com',
    measurementId: 'G-J0DYGRB0JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_HjBa8DcZm7MM7gM1Y_OrLPD_10iuXfE',
    appId: '1:12790717908:android:ee7e4fc6bad1e833f60a41',
    messagingSenderId: '12790717908',
    projectId: 'nevents-final',
    storageBucket: 'nevents-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCz23JU-vIS2WyJ9Uh5OtgY9hT_7BVe_c',
    appId: '1:12790717908:ios:ea747ab3865cc4dcf60a41',
    messagingSenderId: '12790717908',
    projectId: 'nevents-final',
    storageBucket: 'nevents-final.appspot.com',
    iosBundleId: 'com.example.neventsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCz23JU-vIS2WyJ9Uh5OtgY9hT_7BVe_c',
    appId: '1:12790717908:ios:5294b06dc6d5914ff60a41',
    messagingSenderId: '12790717908',
    projectId: 'nevents-final',
    storageBucket: 'nevents-final.appspot.com',
    iosBundleId: 'com.example.neventsAdmin.RunnerTests',
  );
}
